# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java/Cpp CI with Maven/Make

on:
  push:
    branches: [ maven ]
  pull_request:
    branches: [ maven ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build signalserver, signalserverHD and signalserverLIDAR
      working-directory: src/main/resources/Signal-Server/src
      run: make install
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven with debug logging
      run: mvn -X -e -B package --file pom.xml
